; RAK 4631/4630 board - LTO battery variant
; Reuses env:rak4631 and only adds the LTO cell type define
[env:rak4631_lto]
extends = env:rak4631
board_level = pr
board_check = true

build_flags =
  ${env:rak4631.build_flags}
  -I variants/nrf52840/rak4631_lto
  -DCELL_TYPE_LTO=1